import QueryWrapper from "./QueryWraper";
import Header from "./auth/Header";
import Footer from "./components/Footer";

import "./styles/globals.css";

export const metadata = {
  title: "Everience Jobs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <QueryWrapper>
          {/* @ts-expect-error Server Component */}
          <Header />
          <main>{children}</main>
          <Footer />
        </QueryWrapper>
      </body>
    </html>
  );
}
